In [1]:
import numpy as np

Criando uma lista

In [4]:
minhaLista = [0 , 1, 2 , 3 , 4 , 5 , 6, 7, 8]

Convertendo a lista em Array Numpy


In [5]:
meuArray = np.array(minhaLista)

Diferença entre array e print(array)

In [6]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
print (meuArray)

[0 1 2 3 4 5 6 7 8]


Uma forma mais simples de criar a lista

In [8]:
minhaLista = list(range(9))

Transformando essa lista em um Array Numpy

In [9]:
array1 = np.array(range(9))

Arange: fazendo as etapas anteriores numa única sintaxe

In [10]:
array2 = np.arange(9)

In [11]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Start, stop, step

In [37]:
array3 = np.arange(0 , 10, 0.5)

In [38]:
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Arredondando os valores obtidos:

In [22]:
novoArray = np.around (array3)

In [23]:
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

Também podemos forçar o tipo dos elementos

In [39]:
array3 = np.arange(0 , 10, 1.5 ,dtype=int)

In [40]:
array3

array([0, 1, 2, 3, 4, 5, 6])

Também podemos pré-determinar o tipo dos elementos

In [46]:
array4 = np.arange (12)

In [47]:
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Acima teremos os números inteiros, mas podemos deixar o meu array previamente preparado para trabalhar futuramente com tipos float

In [48]:
array4 = np.arange(12.)

In [49]:
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Verificando o tipo de objeto

In [50]:
type (array4)

numpy.ndarray

Verificando o tipo dos elementos do array

In [51]:
array4.dtype   #ou print (array4.dtype)

dtype('float64')

Também pode-se criar um array digitando os valores

In [64]:
vetor1 = np.array ([0 , 1 , 2 , 32020 , 4])

In [53]:
print (vetor1)

[0 1 2 3 4]


Selecionando um elemento específico

In [65]:
vetor1[3]

32020

Selecionando um intervalo específico

In [68]:
vetor1[0:4]

array([    0,     1,     2, 32020])

ou também

In [56]:
print (vetor1[0:2])

[0 1]


Criando um array de strings

In [69]:
s = np.array (['Python' , 'Profissional' , 'Java' , 'Água'])

In [70]:
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [80]:
s = np.array ( ['Pyhton', 2 , 'Profissional' , 'Java', "Água"])

In [85]:
s

array(['11', '1233828392391', '2', '3', 'Água'], dtype='<U21')

In [ ]:
s = np.array ( ['Pyhton', 1233828392391 , 'Profissional' , 'Java', "Água"])

In [84]:
s = np.array ( [11, 1233828392391 , 2 , 3, "Água"])

Alterando um elemento do array

In [86]:
vetor1[2] = 10

In [87]:
vetor1

array([    0,     1,    10, 32020,     4])

Incluindo elementos

In [88]:
vetor1[0] = 'Novo elemento'

ValueError: ignored

In [ ]:
vetor1

Último: Um vetor de int que não aceita a parte decimal do float 45.6

In [89]:
vetor1[0] = 45.6

In [90]:
vetor1

array([   45,     1,    10, 32020,     4])